# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "sdhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/fe000c1e-a570-4efd-9d92-6d78b30979b9";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F7A1-577D";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/programing" = {
    device = "/dev/disk/by-uuid/0712bed5-5c2b-4dde-9745-d7f273ea4a9b";
    fsType = "ext4";
  };

  fileSystems."/home/beta/games" = {
    device = "/dev/disk/by-uuid/c6da343e-5eac-4ced-9e6d-70d1d1ac5887";
    fsType = "ext4";
  };

  fileSystems."/home/beta/Downloads" = {
    device = "/dev/disk/by-uuid/bb000583-c4f4-48a2-ac6a-e3919fa3c103";
    fsType = "ext4";
  };

  fileSystems."/home/beta/Music" = {
    device = "/dev/disk/by-uuid/3bc8f9fe-9461-40fe-8c6b-05f20d4ac913";
    fsType = "ext4";
  };

  fileSystems."/home/beta/Videos" = {
    device = "/dev/disk/by-uuid/b199eac0-df8c-4f84-9f98-71cd498677cf";
    fsType = "ext4";
  };
  swapDevices = [ { device = "/dev/disk/by-uuid/39010a2d-9d3b-4190-a708-700e7fcaaee9"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
